version: '3.9'

services:
  ai:
    container_name: AI
    # 환경 설정 부분
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ai_volume:/AI
    command: sh -c "python main.py"
    restart: on-failure
    ports:
      - "5000:5000"
    expose:
      - 5000
    depends_on:
      - celery
      - redis

  celery:
    container_name: celery_service
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "celery -A tasks worker -l info"
    volumes:
      - ai_volume:/AI
    links:
      - redis
    depends_on:
      - redis


  redis:
    container_name: redis
    image: "redis:latest"
    hostname: redis

volumes:
  ai_volume: