# H2 Database Configuration
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
#spring.datasource.url=jdbc:h2:mem:test   # H2 DB ?? ?? (In-Memory Mode)
#spring.datasource.username=sa
#???? H2 ??

#?? mysql??
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://tojaman.mooo.com:3306/custom?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: user
        password: "00000000"
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    jwt:
        secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb


    logging:
      level:
        web: DEBUG