#---
#
#spring:
#  profiles:
#    active: local
#    # include: oauth
##    group:
##      dev:
##        - oauth
#
#
#---
#
#spring:
#  config:
#    activate:
#      profile: dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://my_mysql:3306/customdb?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/customdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: "4886"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    data:
      redis:
        host: localhost # Docker 사용시 컨테이너 이름 사용
        port: 6379
  logging:
    level:
      web: DEBUG